remote_theme: pages-themes/modernist@v0.2.0
title: "davidebisio"
show_downloads: false
# description: [A short description of your site's purpose]
# google_analytics: [Your Google Analytics tracking ID]
baseurl: ""
